import { StyleSheet } from 'react-native';

export const lixeiraStyles = StyleSheet.create({
  
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        padding: 30,
    },
  
    cards:{
        width: '100%',
        height: 200,
        borderRadius: 8,
        padding: 15,
        backgroundColor: 'white',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        marginBottom: 10,
        position: 'relative',
  },
    cardTitle:{
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
        marginBottom: 10,
        backgroundColor: 'rgb(28, 174, 204)',
        padding: 10,
        width: '111%',
        position: 'absolute',
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
  },
    clickToView:{
        flex: 1,
        alignContent: 'center',
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
  },
    clickToViewText:{
        fontSize:16,
        alignContent: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        marginTop: 25,
  },
    cardText: {
    fontSize: 16,
    color: '#333',
    marginTop: 8,
    marginBottom: 12,
    lineHeight: 22,
  },
    modalContainer: {
    flex: 1,
    backgroundColor: '#000000aa',
    color: '#000000aa',
    justifyContent: 'center',
    padding: 20,
    },
    botoesModal:{
    flexDirection: 'row',
    justifyContent: 'space-around',
    position: 'relative',
    top: 80,
    width: '100%',
    },
    titleModal:{
      fontSize: 20,
      fontWeight: 'bold',
      color: 'white',
      padding: 10,
      width: '100%',
      textAlign: 'center',
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      backgroundColor: 'rgb(28, 174, 204)',
    },
    botaoExcluir:{
      color: 'white',
      fontWeight: 'bold',
      backgroundColor: '#e95d5dff',
      padding: 10,
      fontSize: 16,
      borderRadius: 8,
      width: 100,
      textAlign: 'center',
    },
    botaoCancelar:{
      color: 'white',
      fontWeight: 'bold',
      backgroundColor: '#9BA1A6',
      padding: 10,
      fontSize: 16,
      borderRadius: 8,
      width: 100,
      textAlign: 'center',
    }
});